# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bdb62eb99059b91ea890e1129ea803797d5416c749c9aad3ed6fb222dd68e7f69bf2ec1a93f6ac3c52dd57ca4fbcff262588895b3bb6af839fd27fa9225550ac

test:
  secret_key_base: 4a348f4ee546af9d311c1a5ba2121d1b11d56c0346cc0f2097ea56b844ac8cd6568e35f8bd76bc5bd821ccdd1553d006a35b6363d8662576d98e42ad7dab28b0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
